[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
	Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://use.typekit.net https://p.typekit.net https://fonts.googleapis.com; form-action 'self'; script-src 'self'; connect-src 'self' https://api.timeliness.app https://staging-dot-project-tasks-294214.oa.r.appspot.com; img-src 'self' data:; base-uri 'self'; font-src https://use.typekit.net/ https://fonts.gstatic.com"